app:
  eureka-hostname: localhost
  eureka-port: 8761
  server-port: 8181
  application-name: api-gateway
  product-service-context-path: api/product
  order-service-context-path: api/order
  api-docs-path: api-docs
  hostname: localhost

spring:
  application:
    name: ${app.application-name}
  profiles:
    active:
      - local
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
        - id: discovery-server
          uri: http://${app.eureka-hostname}:${app.eureka-port}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://${app.eureka-hostname}:${app.eureka-port}
          predicates:
            - Path=/eureka/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-hostname}:${app.eureka-port}/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: ${app.server-port}

springdoc:
  swagger-ui:
    urls:
      - name: product-service
        url: http://${app.hostname}:${app.server-port}/${app.product-service-context-path}/${app.api-docs-path}
      - name: order-service
        url: http://${app.hostname}:${app.server-port}/${app.order-service-context-path}/${app.api-docs-path}
    path: /swagger-ui.html
